#exo20suitenom
a=int(input("veuillez saisir un entier a"))
b=int(input("veuillez saisir un entier b"))
c=int(input("veuillez saisir un entier c"))
d=int(input("veuillez saisir un entier d"))
e=int(input("veuillez saisir un entier e"))
f=int(input("veuillez saisir un entier f"))
g=int(input("veuillez saisir un entier g"))
h=int(input("veuillez saisir un entier h"))
i=int(input("veuillez saisir un entier i"))
j=int(input("veuillez saisir un entier j"))
liste =(a ,b , c, d , e , f , g , h , i ,j)
max = max(liste)
print("le plus grand de ces 10 nombres est :" , max)
print("le plus grand element à pour rang :" , liste.index(max))